### PR TITLE
fix: modify the addContentTab parameter

### LINKED ISSUE #1425: feat: skip import meta for tab which registered by api
### Description

插件注册的 API 不需要 `import from 'tab?type=meta'` 了，拿不到任何内容，还会导致 MFSU 解析异常

### Solution

tab meta 的临时文件生成时要做判断

### PR DESCRIPTION
**Pull request by wyy0512**
### 🤔 这个变动的性质是？/ What is the nature of this change?

- [ ] 新特性提交 / New feature
- [ ] bug 修复 / Fix bug
- [ ] 样式优化 / Style optimization
- [ ] 代码风格优化 / Code style optimization
- [ ] 性能优化 / Performance optimization
- [ ] 构建优化 / Build optimization
- [ ] 网站、文档、Demo 改进 / Website, documentation, demo improvements
- [ ] 重构代码或样式 / Refactor code or style
- [ ] 测试相关 / Test related
- [ ] 其他 / Other

修改 addContentTab 参数
### 🔗 相关 Issue / Related Issue
close #1425 

### 📝 更新日志 / Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### CODE REVIEW

File: src/features/meta.ts [hunk 1]
```diff
@@ -118,7 +118,7 @@ export const patchRoutes = ({ routes }) => {
         // apply real tab data from id
         route.meta.tabs = route.meta.tabs?.map(id => ({
           ...tabs[id],
-          meta: filesMeta[id],
+          meta: filesMeta[id] ? filesMeta[id] : { frontmatter: { title: tabs[id].title } },
```
Comment (PeachScript) [inline src/features/meta.ts:121]: `toc` 和 `texts` 给个空值？ref: https://github.com/umijs/dumi/blob/13bf238719b1182349306d1ed58767e3631ea769/src/client/theme-api/types.ts#L56

Comment (wyy0512) [reply src/features/meta.ts]: done
