### PR TITLE
fix: fix the bug that the search shortcut key causes the input box to be out of focus

### LINKED ISSUE #1483: bug: 在 demo 页面输入 / 会直接导致焦点跑到右上角搜索区
### Versions

- dumi: 2.x
- node: --
- npm: --
- OS: --
- Browser: Chrome

### Steps to reproduce

1. 在 demo 中写一个输入框
2. 在输入框中尝试输入 / 字符

### What is Expected?

期望能正常输入字符

### What is actually happening?

焦点会跳到右上角搜索区

### PR DESCRIPTION
**Pull request by Wxh16144**
### 🤔 这个变动的性质是？/ What is the nature of this change?

- [ ] 新特性提交 / New feature
- [x] bug 修复 / Fix bug
- [ ] 样式优化 / Style optimization
- [ ] 代码风格优化 / Code style optimization
- [ ] 性能优化 / Performance optimization
- [ ] 构建优化 / Build optimization
- [ ] 网站、文档、Demo 改进 / Website, documentation, demo improvements
- [ ] 重构代码或样式 / Refactor code or style
- [ ] 测试相关 / Test related
- [ ] 其他 / Other

### 🔗 相关 Issue / Related Issue

fixed #1483 

### 📝 更新日志 / Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      fix the bug that the search shortcut key causes the input box to be out of focus     |
| 🇨🇳 Chinese |     修复搜索快捷键导致输入框失焦错误      |

### CODE REVIEW

File: src/client/theme-default/slots/SearchBar/index.tsx [hunk 1]
```diff
@@ -32,7 +37,7 @@ const SearchBar: FC = () => {
     const handler = (ev: KeyboardEvent) => {
       if (
         ((isAppleDevice ? ev.metaKey : ev.ctrlKey) && ev.key === 'k') ||
-        ev.key === '/'
+        (ev.key === '/' && !isInput(ev.target as HTMLElement))
```
Comment (PeachScript) [inline src/client/theme-default/slots/SearchBar/index.tsx:40]: 是不是判断 `document.activeElement` 是否存在即可？ref: https://developer.mozilla.org/en-US/docs/Web/API/Document/activeElement

Comment (Wxh16144) [reply src/client/theme-default/slots/SearchBar/index.tsx:40]: > 判断 `document.activeElement` 是否存在即可

`document.activeElement` 得到的是一个获得焦点的元素？好像有点歧义

Comment (PeachScript) [reply src/client/theme-default/slots/SearchBar/index.tsx:40]: 的确，button 也会 active

**Review by PeachScript — APPROVED** [review]
+1
