### PR TITLE
fix: exclude duplicate url in the sitemap

### LINKED ISSUE #1646: bug: sitemap 生成的列表有重复的
image

### PR DESCRIPTION
**Pull request by youngjuning**
### 🤔 这个变动的性质是？/ What is the nature of this change?

- [x] bug 修复 / Fix bug
### 🔗 相关 Issue / Related Issue

Fix #1646

### CODE REVIEW

File: src/features/sitemap.ts [hunk 1]
```diff
@@ -36,7 +36,9 @@ export default (api: IApi) => {
         // ignore specific paths
         !exclude.includes(route.path) &&
         // ignore dynamic route, such as /~demos/:uuid
-        ![':', '*'].some((char) => route.path.includes(char))
+        ![':', '*'].some((char) => route.path.includes(char)) &&
+        // ignore duplicate URLs
+        route.path !== '' && route.parentId !== undefined
```
Comment (PeachScript) [inline src/features/sitemap.ts:41]: `route.parentId !== undefined` 换成 `!route.isLayout` 吧，`layout` 会有嵌套的情况

File: src/features/sitemap.ts [hunk 2]
```diff
@@ -36,7 +36,9 @@ export default (api: IApi) => {
         // ignore specific paths
         !exclude.includes(route.path) &&
         // ignore dynamic route, such as /~demos/:uuid
-        ![':', '*'].some((char) => route.path.includes(char))
+        ![':', '*'].some((char) => route.path.includes(char)) &&
```
Comment (PeachScript) [inline src/features/sitemap.ts:39]: 代码需要格式化一下

**Review by PeachScript — APPROVED** [review]
+1
